### ISSUE TITLE
Instructions for Cura 2.3+

### ISSUE THREAD

**Issue by keski** [asonawalla/monoprice_cura#1]
It's not clear from the instructions the versions of Cura for which this settings file applies. For example, I was unable to find the ```machines/``` directory in my installation of Cura 2.3+ on El Capitan. For now I'll try downgrading. Really interested in trying the config.

**Comment by asonawalla** [comment]
Good point - this was used with Cura 2.1.3

My printer was out of service for a little while but I should be bringing it back online shortly.  I can take a look at the new software then - if you beat me to it, feel free to submit a PR.

**Comment by keski** [comment]
Tried with Cura 2.1.3 and I'm really impressed by the configuration. Used bed temp of 50°C and printed PLA at at 200°C and had better results than I ever thought would be possible with this printer. Will perhaps consider upgrading Cura later, but actually don't see any arguments for doing so after this print. Thanks!

**Comment by asonawalla** [comment]
Nice!  Glad it's working well.

**Comment by asonawalla** [comment]
@keski A little late here, but I did finally get around to updating this for the newest version of Cura.  Tested on 2.5 and things seem to be working well, and also added some easier installation steps as well!
